syntax = "proto3";

package echo;

option go_package = "echo-server/proto/echo";

import "google/api/annotations.proto";

service EchoService {
  rpc Echo(EchoRequest) returns (EchoResponse) {
    option (google.api.http) = {
      post: "/v1/echo"
      body: "*"
    };
  }

  rpc SlowEcho(EchoRequest) returns (EchoResponse) {
    option (google.api.http) = {
      post: "/v1/echo/slow"
      body: "*"
    };
  }

  rpc FailEcho(EchoRequest) returns (EchoResponse) {
    option (google.api.http) = {
      post: "/v1/echo/fail"
      body: "*"
    };
  }

  rpc DoubleTxEcho(EchoRequest) returns (EchoResponse) {
    option (google.api.http) = {
      post: "/v1/echo/doubletx"
      body: "*"
    };
  }

  rpc FixedTxEcho(EchoRequest) returns (EchoResponse) {
    option (google.api.http) = {
      post: "/v1/echo/fixedtx"
      body: "*"
    };
  }
}

message EchoRequest {
  string message = 1;
}

message EchoResponse {
  string message = 1;
}